trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build './markdown-to-html/markdown-to-html.csproj' --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet pack -c Release -o '$(Build.ArtifactStagingDirectory)' './markdown-to-html/markdown-to-html.csproj' /p:Version=2.0.$(Build.BuildId)
  displayName: 'dotNet pack'

- task: PublishBuildArtifacts@1

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget'

